### ISSUE TITLE
Unlimited QuickSave Deleted?

### ISSUE THREAD

**Issue by mrgee-host** [WolvenKit/BraindanceProtocol#10]
Can you make unlimited quicksave?

**Comment by osulli** [comment]
@cyberbug-2077 as in unlimited quick save slots before they start rotating or?

I think the default is 3, instead of unlimited how does 10 sound? Or 20?

**Comment by mrgee-host** [comment]
Yes, thanks you.

**Comment by mrgee-host** [comment]
You delete the quicksave on new update?

**Comment by osulli** [comment]
Nope https://github.com/WolvenKit/BraindanceProtocol/blob/main/mods/braindance_protocol/engine/saves.lua#L30

**Comment by mrgee-host** [comment]
Hmm, I downloaded the latest release and its not there.
Then, I try to copy from your link, but in the game its give me error that says SaveSlotsConfig or NumQuickSaveSlots not in game..
And the other autosvae function syays "Saves.DisableAutosaves()" not float

**Comment by kristoferblack** [comment]
@cyberbug-2077 This is inadvertently removed from the last release. The v1.0.0 version we just released here restores that functionality. 

In this release, command use has changed. In console, you'll want to start with: 

`BD = GetMod("braindance_protocol")`

Then you can use the commands such as:

`BD.Saves.DisableAutosave()`
`BD.Saves.IncreaseQuicksaves()`

Feel free to pop into Discord if you have any further issue.
