### ISSUE TITLE
Chinese in a Lua script can not be displayed correctly in the front end

### ISSUE THREAD

**Issue by 2217936322** [WolvenKit/BraindanceProtocol#107]
## Description
A brief, concise, summary of your issue.

## Expected Behaviour
A short summary of expected behaviour.

## Actual Behaviour
A short summary of the actual behaviour.

## Replication Steps
Short, bullet-pointed, replication steps.

![QQ截图20210820100151](https://user-images.githubusercontent.com/19187989/130167565-af8edc36-3dbf-4f7a-bc98-b8f897968a47.png)
![2](https://user-images.githubusercontent.com/19187989/130167611-f43bfc68-994a-4bc1-91f4-6f68de99cccf.png)

**Comment by Nats-ji** [comment]
可以参考这个
https://wiki.redmodding.org/cyber-engine-tweaks/v/jian-ti-zhong-wen-chinese/getting-started/configuration/change-font-and-font-size#ru-he-xian-shi-fei-ying-wen-zi-fu
