### ISSUE TITLE
BD.Cheats.Legend.Create() - Should items be upgradable after using this command

### ISSUE THREAD

**Issue by Sayne86** [WolvenKit/BraindanceProtocol#15]
Hello, forgive me if this is the wrong way to ask this, I'm new to GitHub.

When using the BD.Cheats.Legend.Create() command to make all my equipped items Legendary with max slots, how does this command interact with the built-in Upgrading system?

In testing just now, I took several items I had on my V and executed the command.  It worked!  But when I went into the Crafting Upgrades menu, I could still upgrade the items, though now they were of Legendary quality so they took legendary components to max out. 

Thanks!

**Comment by osulli** [comment]
'Tis the right place for Questions/Issues/Requests.

@specik wrote that cheat (source code here: https://github.com/WolvenKit/BraindanceProtocol/blob/main/mods/braindance_protocol/cheats/legend.lua)


It runs the following:

```
	cs = ssc:Get(CName.new('CraftingSystem'))

				cs:SetItemLevel2(itemdata)
				Game['gameRPGManager::ForceItemQuality;GameObjectgameItemDataCName'](player, itemdata, CName.new('Legendary'))
```

I don't personally know enough about the game systems to explain why you're facing this behaviour as, to me, it looks like it is interacting using the native systems.
One thing I would suggest is when using modification cheats like this you exit/enter the menu, or better yet save and load.
I found when modifying stats in Cheat Engine would cause really strange, similar to what you're facing, behaviour. Save and Load immediately fixed it.

**Comment by Sayne86** [comment]
OK thank you!

I will test it by saving after I upgrade the items and reload that save and report back what it does.

Also, since I have you really quick... the latest release of this seems to have auto-enabled that vehicles don't knock down the player.  Not sure if that is intentional.

**Comment by osulli** [comment]
Thank you for letting me know! It has been enabled actually since commit 1! Feel free to remove it from your file

**Comment by Sayne86** [comment]
OK after a bit of testing, for me at least, it does not seem to have much if any affect on the item's STATS or the number of upgrades required before clothing items become un-upgradable.

For my level 23 character, I can craft green trousers which I can upgrade 28 times before they won't upgrade any farther.  If I turn those legendary, they still take 28 upgrades before they won't upgrade any farther... they just take may more components to upgrade.

For weapons, the process seems to add two or three levels to the item.  If you've got a maxed-out weapon in one of your equipment slots, that weapon will gain a few levels and become impossible to unequip from your holster slot until you level up.

**Comment by kristoferblack** [comment]
Hey there @Sayne86. Thanks for the report. I don't have an answer for you regarding the ability to upgrade the items after they have been made Legendary. There is still a lot we don't know about how the crafting system works under the hood. 

Regarding the weapons upgrading beyond your level, its something that happens if you've been upgrading your weapons via the crafting system. No way around that at this point. This will probably change in the future as we learn more. 

If you want to discuss this further, please free free to drop into the Discord. For now, I'm closing this issue. Thanks!

**Comment by Sayne86** [comment]
No worries!  I didn't expect a solution, just wanted to report my findings.

The whole crafting and upgrading system is such an arcane jumble that I'm sure it'll take folks a long time to disentangle and fully understand.
