### ISSUE TITLE
Problems with DisableAutosave() and IncreaseQuickSaves()

### ISSUE THREAD

**Issue by Nicofisi** [WolvenKit/BraindanceProtocol#16]
Hello!

## Saves.DisableAutosave()

https://github.com/WolvenKit/BraindanceProtocol/blob/4ab3a78b7a33afd80c589f57a19c77367c4264b5/mods/braindance_protocol/engine/saves.lua#L10
Is this expected to work? Because it doesn't for me, the command errors, from what I can see it should be `SetBool`

## Saves.IncreaseQuicksaves()

https://github.com/WolvenKit/BraindanceProtocol/blob/4ab3a78b7a33afd80c589f57a19c77367c4264b5/mods/braindance_protocol/engine/saves.lua#L33
Same here, has someone tested whether this works? It errors for me as there is no such thing as `SaveSlotsConfig`, there is only `Developer/SaveSlotsConfig` as can be seen here:

https://github.com/WolvenKit/BraindanceProtocol/blob/4ab3a78b7a33afd80c589f57a19c77367c4264b5/dumps/settings.ini#L412

I tried running `GameOptions.SetInt("Developer/SaveSlotsConfig", "NumQuickSaveSlots", 10)` and it showed as success, I also tried adding it to the `autoexec.lua`, but after reloading the game, the value is set, but pressing f5 still only keeps using slots 0 1 2, not more. Any ideas?

**Comment by Nicofisi** [comment]
## Visual.Rain(state)

It will probably be the same issue here:
https://github.com/WolvenKit/BraindanceProtocol/blob/18575e9ca6f5b8d663fbfec579ac763c1d1abeb8/mods/braindance_protocol/engine/visual.lua#L9

- it is `Developer/FeatureToggles`
- it is a Bool, not a Float

**Comment by kristoferblack** [comment]
@Nicofisi Let me do some testing on this. Could have just been a result of a bad copy/paste somewhere. Stay tuned

**Comment by Nicofisi** [comment]
Interestingly enough I've just added a new file - `C:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077\engine\config\platform\pc\myini.ini`, and put this inside:
```
[Developer/SaveSlotsConfig]
NumQuickSaveSlots=10
```
now the new save slots work. It didn't work though when I used the `autoexec.lua` file to execute the command, as I stated above.

It probably means that the number is read intro some variable by the game engine before the autoexec file is executed by cyber-engine-tweaks? That's a little unfortunate

![obraz](https://user-images.githubusercontent.com/12614053/103575795-849e5600-4ed2-11eb-80ee-d5d20f22ce34.png)

**Comment by kristoferblack** [comment]
Okay here's an update. You were right. These functions weren't being called to set the correct types. I fixed and tested them, so they will be included in the next release of the mod. Thanks for catching this! 

That trick adding an INI for the save options is smart, I'll add that to the Wiki for others. And yeah, its likely the game reads it from somewhere in memory and sets it accordingly, possibly repeatedly. The INI method seems to become the source of truth for that value if it exists in there. I'm betting the same would work for AutoSavePeriod and AutoSaveEnabled.

**Comment by QuantumKitten** [comment]
Been messing with the Toggle Rain thing. Tried BD. GameOptions.SetFloat("FeatureToggles", "RainMap", true)

And a few other things but no beuno yet. Has anyone had luck with rain toggle?

**Comment by kristoferblack** [comment]
What you want is `GameOptions.SetBool("FeatureToggles", "RainMap", true)`.

That doesn't actually make it rain. I think it toggles whether rain is rendered or not. So if you set it to false, presumably it wouldn't rain ever. Not sure tho.

**Comment by osulli** [comment]
That's correct, it feature toggles rain. Not 'rainNow', just 'can it ever rain'.

And thanks for fixing the janky type :)
