### ISSUE TITLE
All Achievements not working

### ISSUE THREAD

**Issue by kryptic-x** [WolvenKit/BraindanceProtocol#18]
All achievements command not working

Supposed to unlock all achievements

Doesnt give error but does nothing

Tried 1, Steam, All etc but nothing works

**Comment by sunilrav** [comment]
https://wiki.cybermods.net/cyber-engine-tweaks/console/functions/global#game-unlockallachievements says `Game.UnlockAllAchievements()` is till a work in progress, so I guess that is why it is not working.

I wonder if we can use 
`UnlockAchievement(achievement : ref:Achievement_Record);`
shown at https://wiki.cybermods.net/cyber-engine-tweaks/console/functions/systems/achivementsystem 
to somehow aggregate all achievements. 

But I am not yet sure how to use it. If any one can point me in the right direction, I can further take a look.

**Comment by sunilrav** [comment]
Can anyone let me know if this looks good. I will submit a pull request.
https://github.com/sunilrav/BraindanceProtocol/commit/a46f53e9e0ebd333a605a28db852ee1360d230c1

Hard to test because I already used Game.UnlockAllAchievements() to get all the achievements.

**Comment by osulli** [comment]
Yep if you think this will solve it, it is a harmless change. Please go ahead and PR :)

**Comment by archraziel** [comment]
I just tested here(GOG) and is working. But I had to edit the init.lua file on my machine, this fix is not on the last version 1.1.1.

**Comment by osulli** [comment]
@archraziel are you saying `init.lua` needs updating? or was this just localised to you?
