### ISSUE TITLE
BD.Cheats.Player.AddMoney(amount) doesn't work. 

### ISSUE THREAD

**Issue by ArsenicTouch** [WolvenKit/BraindanceProtocol#19]
## Description
BD.Cheats.Player.AddMoney(amount) doesn't do anything.

## Expected Behaviour
Supposed to give money.

## Actual Behaviour
Nothing happens. 

## Replication Steps
Step 1: Enter BD = GetMod("braindance_protocol")
Step 2: Enter BD.Cheats.Player.AddMoney(50000)
Step 3: ????

**Comment by Kojima648** [comment]
There are also some inefficiencies, such as upgrading the quality of equipment

**Comment by osulli** [comment]
Suggestions and Pull Requests to source code welcome!

**Comment by ArsenicTouch** [comment]
> 
> 
> There are also some inefficiencies, such as upgrading the quality of equipment

This one should be working. Though there is a newer version of the script that expired came up with.

**Comment by osulli** [comment]
Feel free to update the script with Expired's :) !

**Comment by osulli** [comment]
Fixed
