### ISSUE TITLE
prevent vehicle knd is enabled by default and can't be turned off

### ISSUE THREAD

**Issue by Furyah** [WolvenKit/BraindanceProtocol#23]
Is there a way to turn off no vehicle knd? I'd like to keep it but still use the no autosave command.

**Comment by osulli** [comment]
Yes, remove it from the init script.

**Comment by osulli** [comment]
Done by default for next release
https://github.com/WolvenKit/BraindanceProtocol/commit/d907dfa12561e6badd09a96c5f336039d314ccda
