### ISSUE TITLE
savegame commands don't work at all and toggle rain is missing

### ISSUE THREAD

**Issue by Furyah** [WolvenKit/BraindanceProtocol#24]
The increase quick save slots and disable autosave commands simply don't do anything. The give money command doesn't do anything but at least it says: "executing protocol." Inputting commands related to saves don't produce any response from the console. 

[edit] And the toggle rain command is missing from the command list.

**Comment by osulli** [comment]
I think this was fixed in the latest release

**Comment by Sayne86** [comment]
Hello,

Any word on the toggle rain command?  There's code referring to toggling the rain on and off in the visual.lua file, but I can't figure out how to activate it.

Thanks

**Comment by osulli** [comment]
It's more like 'Toggle rain ever appearing in game vs NOT' as opposed to 'TURN RAIN ON/OFF NOW'

e: Open new issue for rain if comment above doesn't solve issue.
