### ISSUE TITLE
Can't run the mod

### ISSUE THREAD

**Issue by ccrofts17** [WolvenKit/BraindanceProtocol#29]
When I attempt to run the mod I get this error message:
`lua: error: [string "BD = GetMod("braindance_prot..."]:1: attempt to call a nil value (global 'GetMod')`

**Comment by osulli** [comment]
Sounds like you're on old CET version.

**Comment by ccrofts17** [comment]
Yeah, that ended up being the case.  When I downloaded the .zip, I ended up downloading the source for the repository, rather than the just the necessary files for 1.8.3.  I copied everything into the correct location, but for some reason when I copied the source itself, it was actually running on a previous version.  After replacing the files with the ones from the correct .zip, it appeared to be the correct version.
