### ISSUE TITLE
Male V and river, female V and Paran, After entering the code, no intimacy options will be generated

### ISSUE THREAD

**Issue by Kojima648** [WolvenKit/BraindanceProtocol#40]
BD.Cheats.Facts.SetRiverRomance() -- River is now romanceable
BD.Cheats.Facts.SetPanamRomance() -- Panam is now romanceable

**Comment by osulli** [comment]
?

**Comment by Kojima648** [comment]
> 
> 
> ?

I am the male character V. During the mission of "River of Love", I entered the code with the river family before eating, and then went to the top of the tower to drink, but there would be no intimate conversations in the process. I was directly rejected by the river.

**Comment by ghost** [comment]
I'm not sure if the commands force it to work, if you're male V.

From: [PowerPyx](https://www.powerpyx.com/cyberpunk-2077-river-ward-romance-guide/)
> Important: River is Heterosexual and only likes Girls. He can only be romanced when playing as a female Character (Female Body Type). This Romance is unavailable for Males! As a Male you can still play his quests but he will block your romantic attempts.

AFAIK, the command is supposed to work, if you're female V (in this case with River), if you accidentally made the "wrong" romantic choices throughout his questline. The command should "correct" your mistakes, making it possible for female V to romance River.

**Comment by Nats-ji** [comment]
Panam romanceable has been known to not work. Maybe should consider removing it. Not sure about River, I would suggest you run this command before triggering the Peralez's side quest

**Comment by Kojima648** [comment]
> 
> 
> I'm not sure if the commands force it to work, if you're male V.
> 
> From: [PowerPyx](https://www.powerpyx.com/cyberpunk-2077-river-ward-romance-guide/)
> 
> > Important: River is Heterosexual and only likes Girls. He can only be romanced when playing as a female Character (Female Body Type). This Romance is unavailable for Males! As a Male you can still play his quests but he will block your romantic attempts.
> 
> AFAIK, the command is supposed to work, if you're female V (in this case with River), if you accidentally made the "wrong" romantic choices throughout his questline. The command should "correct" your mistakes, making it possible for female V to romance River.

@Nats-ji  Generally speaking, although the plot of the game is set like this, if the script doesn't work, I think it should be removed.

**Comment by osulli** [comment]
Fair enough - if it doesn't work I'll remove it.

**Comment by osulli** [comment]
Panam/River romance removed
