### ISSUE TITLE
[CI] Update scripts and config to support NMM installs

### ISSUE THREAD

**Issue by osulli** [WolvenKit/BraindanceProtocol#45]
## Description
Ensure NMM can install BD

## Further Details
Rather than change the repo structure, it would be wise to modify the CI scripts to do this with archiving

**Comment by ghost** [comment]
Didn't you do that [here](https://github.com/WolvenKit/BraindanceProtocol/blob/main/tools/nexus.sh)?

**Comment by osulli** [comment]
Indeed

**Comment by Nats-ji** [comment]
Now automatically creates archives for nexus and cybermods when making a new relesae.
https://github.com/WolvenKit/BraindanceProtocol/commit/ad4f4066422124057f8258587963155b8c69e52c
