### ISSUE TITLE
Vehicle Knockdown missing from GUI

### ISSUE THREAD

**Issue by osulli** [WolvenKit/BraindanceProtocol#47]
## Description
Vehicle knockdown tweak is missing from the GUI.

![image](https://user-images.githubusercontent.com/46930728/105153833-ccdb8c00-5b00-11eb-9a08-821ae303eb1c.png)

**Comment by osulli** [comment]
Workaround:

```lua
-- In CET console

BD = GetMod("braindance_protocol")
BD.Vehicles.PreventKnockdown()
```

**Comment by Nats-ji** [comment]
Fixed
