### ISSUE TITLE
BD.Cheats.Legend.Create() does not add missing mod slots to existing legendaries since patch 1.1

### ISSUE THREAD

**Issue by weezedog** [WolvenKit/BraindanceProtocol#51]
Since patch 1.1 BD.Cheats.Legend.Create() will not add missing mod slots when upgrading existing legendaries. Example: using cheat on legendary pants with only 1 mod slot does not upgrade pants to have 3 mod slots like it used to pre-patch.  

If you use the cheat on a non-legendary quality item, it does upgrade it to legendary with the max number of mod slots, but it does not seem to be working on items that are already legendary. This may have something to do with the changes in patch 1.1 that stops you from re-rolling legendaries by re-loading a save game, but I am not sure.

**Comment by osulli** [comment]
I think you have answered your own question. With nothing having changed on the BD side, must be the re-roll.
Once we have access to object properties we can force these sorts of, well, properties.

**Comment by weezedog** [comment]
I thought a workaround could be to downgrade the legendary to a lower quality, then upgrade it back to legendary since upgrading common/uncommon/rare/epic items seems to add all the mod slots still. But I have not figured out how to do that, but I believe it’s possible with the Modify protocol?

**Comment by osulli** [comment]
Give it a go! 

Modify your local file here https://github.com/WolvenKit/BraindanceProtocol/blob/main/mods/braindance_protocol/cheats/legend.lua#L51

Then in CET, reload the mod 
Then test

If it works either send me the snippet here or submit a PR :)

**Comment by weezedog** [comment]
No go. Downgrading the item just seemed to hide the number of mod slots on the item. Upgrading the item to legendary from there just restored the exact same number of slots with the exact same mods that were in the item as before.

**Comment by ghost** [comment]
I might have a fix for this.. Will do a commit/pull-request if it works. I'm testing atm.

**Comment by ghost** [comment]
It should now be fixed in v1.5.4
