### ISSUE TITLE
Utility.Player.Respec()

### ISSUE THREAD

**Issue by osulli** [WolvenKit/BraindanceProtocol#6]
- Adds tabula resa
- Resets attributes (calculation required?)

**Comment by osulli** [comment]
```
--[[
    Game.AddToInventory("Items.PerkPointsResetter",1)

    GetAttribute levels + add together and set attribute points to that
 ]]
```

**Comment by djgamerr** [comment]
I would LOVE to see this as a feature
its a bummer that I would have to restart the game just because i specced wrongly in the beginning...

**Comment by osulli** [comment]
@djgamerr FWIW - you could use Cheat Engine or Lua commands to give yourself 100k.
- Go to any Ripperdoc
- Buy tabula resa (this restores perk points)
- Use Cheat engine or Lua to reset all your attributes to 1
- Use CE or Lua to set your levels or attribute points to match
