### ISSUE TITLE
Missing mouse cursor

### ISSUE THREAD

**Issue by ZeroSuf3r** [WolvenKit/BraindanceProtocol#62]
> 
> ## Description
> 
> Opening menu will not activate mouse cursor
> ## Expected Behaviour
> 
> Mouse cursor should appear when menu opened and let you choose options
> ## Actual Behaviour
> 
> Cursor doesn't appear, menu stays on screen, V moves freely around
> ## Replication Steps
> 
> Step 1: Bind key for menu via CyberEngineTweaks
> Step 2: Press key to activate menu
> ## Workaround
>
> Step 1: Open CyberEngineTweaks menu, cursor appears
> Step 2: Open BraindanceProtocol menu
> Step 3: Select wanted options
> Step 4: Profit?

**Comment by ZeroSuf3r** [comment]
Took a look into nexus mods, it's seems i got answer for my question. 

> Glacknarf:
>
> CET team reports that this is 'currently' by design, to avoid bringing up accidental menus when playing (with K+M, can't imagine that would ever be an issue using a controller) -- which, when you think about it, makes a lot of sense.
> 
> CET MUST be open + press your hotkeys to then use BD GUI.
> 
> UX expected to improve in future releases. 

Providing link to forum: https://www.nexusmods.com/cyberpunk2077/mods/616?tab=posts

As of now closing as this "problem" comes from CyberEngineTweaks

**Comment by osulli** [comment]
Thanks. That's my username on Nexus BTW.
