### ISSUE TITLE
Fix God Mode & Add Infinite Ammo & Remove quest flags from items

### ISSUE THREAD

**Issue by ZeroSuf3r** [WolvenKit/BraindanceProtocol#66]
## Additional Features

- [x] God mode
- [x] Infinite ammo
- [x] Quest flag removal from items

**Comment by ghost** [comment]
I added the 

> Remove yellow mark for items and make them removable from inventory

Here: https://github.com/WolvenKit/BraindanceProtocol/pull/69 . It's merged with main

**Comment by osulli** [comment]
Infinite Ammo is technically done.
I'll allow others to decide if this can be closed.

The protocol allows the player to just add large amounts of money.
If there is a trigger for firing or a way to poll every .5 seconds and add ammo silently that would be good.

**Comment by ZeroSuf3r** [comment]
How about bindable key? Let's say on each reload ammo would be added automatically?
For example it could be "R" key. (let the user decide which key in CyberEngineTweaks bind menu)

**Comment by ghost** [comment]
> How about bindable key? Let's say on each reload ammo would be added automatically?
> For example it could be "R" key. (let the user decide which key in CyberEngineTweaks bind menu)

That should actually already be possible in [v1.6.0](https://github.com/WolvenKit/BraindanceProtocol/tree/1.6.0). Not many hotkeys yet, but refill ammo is [one of them](https://github.com/WolvenKit/BraindanceProtocol/blob/3b5eeb01bcf1076c75f7abd4b13603efb4b8d384/mods/braindance_protocol/init.lua#L44).

**Comment by ZeroSuf3r** [comment]
> 
> 
> > How about bindable key? Let's say on each reload ammo would be added automatically?
> > For example it could be "R" key. (let the user decide which key in CyberEngineTweaks bind menu)
> 
> That should actually already be possible in [v1.6.0](https://github.com/WolvenKit/BraindanceProtocol/tree/1.6.0). Not many hotkeys yet, but refill ammo is [one of them](https://github.com/WolvenKit/BraindanceProtocol/blob/3b5eeb01bcf1076c75f7abd4b13603efb4b8d384/mods/braindance_protocol/init.lua#L44).

Damn it, didn't check for hotkeys, my fault.
Thanks for updates guys ;) Closing as it solved for me.
