### ISSUE TITLE
Can't seem to open the UI after update to latest

### ISSUE THREAD

**Issue by mikeechen** [WolvenKit/BraindanceProtocol#79]
## Description
After updating CET to 1.10.0, BD protocol to 1.6.1, the UI can't seem to be opened. I checked the logs, and this is the error I'm seeing: 
`[2021-02-05 16:43:40 UTC-08:00] [error] ...ns\cyber_engine_tweaks\mods\braindance_protocol\init.lua:57: attempt to index a nil value (global 'protocols')
stack traceback:
	...ns\cyber_engine_tweaks\mods\braindance_protocol\init.lua:57: in function <...ns\cyber_engine_tweaks\mods\braindance_protocol\init.lua:50>`

## Expected Behaviour
UI to be opened

## Actual Behaviour
UI can't be opened

## Replication Steps
- update CET and BD protocol to the latest versions
- open cyberpunk
- bind BD protocol UI key to B, or any key
- click on the key bind to opening the UI
- nothing opens

**Comment by Nats-ji** [comment]
Please do a clean installation

**Comment by mikeechen** [comment]
Yup just tried that. Re-thought this whole init being broken thing. Thanks!

**Comment by Nats-ji** [comment]
no problem
