### ISSUE TITLE
Menu open with CyberEngineTweaks console key

### ISSUE THREAD

**Issue by ZeroSuf3r** [WolvenKit/BraindanceProtocol#82]
## Description
Open menu with CyberEngineTweaks console

## Code Snippets and Documentation
```
registerForEvent("onOverlayOpen", function()
	drawWindow = true
end)
registerForEvent("onOverlayClose", function()
	drawWindow = false
end)
```

## Further Details
Make this option choosable for user how they wants to menu appear.

## Summary
Personally for me this is best method, I don't need to press too many hotkeys for menus to appear. One hotkey for all of menus.

**Comment by ghost** [comment]
Totally forgot about this, should work now: https://github.com/WolvenKit/BraindanceProtocol/pull/89
