### ISSUE TITLE
Release 1.7.3 - Can no longer collapse Braindance Protocol interface when desired

### ISSUE THREAD

**Issue by TimeDiver0** [WolvenKit/BraindanceProtocol#91]
## Description
Unable to collapse the Braindance Protocol interface as of release 1.7.3 (no triangle-like symbol to do so).

## Expected Behaviour
Attempts to circumvent this by editing 'Collapsed=0' to 'Collapsed=1' in layout.ini does not do so either.

**Comment by ghost** [comment]
Not sure what exactly you mean.. Collapsing the sub-menus, like Cheats, Crafting Recipes etc? That works fine for me atleast.
Or do you mean collapsing / hiding the entire BDP mod GUI? That's still possible with your chosen keybind, whenever the CET console is closed.

Sub-menu collapsing test (v1.7.3)
https://i.imgur.com/KZYGkCF.gif

Opening and closing BDP when CET console is closed (v1.7.3):
https://i.imgur.com/WzrdLRu.gif

**Edit**: Did you do a clean install, removing the old `braindance_protocol` folder? And what version of CET are you using?

**Comment by TimeDiver0** [comment]
> Not sure what exactly you mean.. Collapsing the sub-menus, like Cheats, Crafting Recipes etc? That works fine for me atleast.
> Or do you mean collapsing / hiding the entire BDP mod GUI? That's still possible with your chosen keybind, whenever the CET console is closed.

To clarify, I am looking minimize Braindance Protocol's interface (while enabled via the Cyber Engine Tweaks console hotkey)  _without_ having to use a dedicated keybinding, yes. Per the following example image:

https://i.imgur.com/UNi7fcH.png

Note that while the Cyber Engine Tweaks interface is 'expanded' (with the console enabled), the others (with the exception of Braindance Protocol) are 'minimized', for lack of a better term, with no means to do the same with Braindance Protocol (the lack of a triangle symbol).

> **Edit**: Did you do a clean install, removing the old `braindance_protocol` folder? And what version of CET are you using?

Indeed; with the exception of a single modified file (/utility/shopper.lua) to which I have added a number of functions (and re-edit with each new release), I remove all previous traces of previous versions.

**Comment by ghost** [comment]
Looks like it's fixed in the '[overhaul](https://github.com/WolvenKit/BraindanceProtocol/tree/overhaul)' branch 👍
